### ISSUE TITLE
STT0070: Evaluate the performance of sp wav2vec2 model and yash model on our benchmark dataset.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-model-evaluation#1]
### Description 
we need to evaluate the latest wav2vec2 model of sp and yash on the new benchmark dataset we have created. evaluate the overall cer and wer on test dataset and also for each department. 
Make a detailed documentation on how many samples and hours plus the spec of GPUs used to train the particular models.
[benchmark](url)
### Completion Criteria 
A detailed documentation of models performance in stt-documentation wiki page. 

### Implementation. 
1. Download the benchmark dataset from hugging face.
2. Run an inference on the benchmark dataset using the sp model and yash model. 
3. find the overall cer(character error rate) of each model.
4. find the cer on each department by each model.
5. update the asr training cer with the data from both models.

### Subtask 
- [x] download the benchmark dataset from hf. 
- [x] run the inference on audio using sp and yash model and save the inference transcript in separate column. 
- [x] compute the overall cer of each models.
- [x] compute the cer of each model department wise. 
- [x] update the model performace documentaion in asr training history.
